export enum ActivityType {
	CREATED_CHART = "CREATED_CHART",
	CREATED_TOUR_PASS = "CREATED_TOUR_PASS",
	CREATED_THEME = "CREATED_THEME",
	LIKED_CHART = "LIKED_CHART",
	LIKED_TOUR_PASS = "LIKED_TOUR_PASS",
	LIKED_THEME = "LIKED_THEME",
	BOOKMARKED_CHART = "BOOKMARKED_CHART",
	BOOKMARKED_TOUR_PASS = "BOOKMARKED_TOUR_PASS",
	BOOKMARKED_THEME = "BOOKMARKED_THEME",
	FOLLOWED_USER = "FOLLOWED_USER",
}
