export enum StreamingPlatform {
	SPOTIFY = "SPOTIFY",
	APPLE_MUSIC = "APPLE_MUSIC",
	YOUTUBE_MUSIC = "YOUTUBE_MUSIC",
	DEEZER = "DEEZER",
	TIDAL = "TIDAL",
	AMAZON_MUSIC = "AMAZON_MUSIC",
	SOUNDCLOUD = "SOUNDCLOUD",
	LAST_FM = "LAST_FM",
}
